/////////////////////////////////////////////////////////////////////////////
// Name:        actuator_dlg.h
// Purpose:     dialog for FGActuator
// Author:      Jon Berndt
// Created:     04/12/2007
// Copyright:   (c) Jon Berndt
// Licence:     GPL licence
/////////////////////////////////////////////////////////////////////////////

// -*- C++ -*- generated by wxGlade 0.4.1 on Fri Apr 06 07:40:41 2007

#ifndef ACTUATORCOMPONENTEDITOR_H
#define ACTUATORCOMPONENTEDITOR_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
#include <wx/notebook.h>
#include <wx/tglbtn.h>
// end wxGlade

class Actuator;

class ActuatorComponentEditor: public wxDialog {
public:
    // begin wxGlade: ActuatorComponentEditor::ids
    // end wxGlade

    ActuatorComponentEditor(Actuator *actuator, wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: ActuatorComponentEditor::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: ActuatorComponentEditor::attributes
    wxStaticBox* sizer_inout_staticbox;
    wxStaticBox* sizer_actuator_properties_staticbox;
    wxStaticBox* sizer_clip_staticbox;
    wxStaticBox* sizer_basic_staticbox;
    wxStaticText* label_name;
    wxTextCtrl* txtEd_Name;
    wxStaticText* label_type;
    wxTextCtrl* txtEd_Type;
    wxStaticText* label_order;
    wxTextCtrl* txtEd_Order;
    wxCheckBox* chx_Clip;
    wxStaticText* label_clip_min;
    wxTextCtrl* txtEd_MinClip;
    wxStaticText* label_clip_max;
    wxTextCtrl* txtEd_MaxClip;
    wxStaticText* label_7;
    wxTextCtrl* txtEd_Lag;
    wxStaticText* label_10;
    wxTextCtrl* txtEd_RateLimit;
    wxStaticText* label_11;
    wxTextCtrl* txtEd_Hysteresis;
    wxStaticText* label_17;
    wxTextCtrl* txtEd_Bias;
    wxStaticText* label_1;
    wxToggleButton* button_invert_input;
    wxTextCtrl* txtEd_InputProperty;
    wxStaticText* label_output_property;
    wxTextCtrl* txtEd_OutputProperty;
    wxPanel* notebook_1_pane_1;
    wxTextCtrl* txtEd_Description;
    wxNotebook* nbk_Properties;
    wxButton* button_OK;
    wxButton* button_Cancel;
    wxButton* button_Help;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void OnCheckboxClip(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnClickInvertInput(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnButtonPressOK(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnButtonPressCancel(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnButtonPressHelp(wxCommandEvent &event); // wxGlade: <event_handler>

    void GetDataIn(Actuator * g);
    void SetDataOut(Actuator * g);
    bool Show(bool);
    
private:
    wxString name;
    wxString description;
    wxString order;
    bool clipable;
    wxString clip_max;
    wxString clip_min;

}; // wxGlade: end class

#include "actuator.h"

#endif // ACTUATORCOMPONENTEDITOR_H
