/////////////////////////////////////////////////////////////////////////////
// Name:        sensor_dlg.h
// Purpose:     dialog for FGSensor
// Author:      Jon Berndt
// Created:     07/19/2006
// Copyright:   (c) Jon Berndt
// Licence:     GPL licence
/////////////////////////////////////////////////////////////////////////////

// -*- C++ -*- generated by wxGlade 0.4.1 on Sat Jul 15 08:54:44 2006

#ifndef SENSORCOMPONENTEDITOR_H
#define SENSORCOMPONENTEDITOR_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
#include <wx/notebook.h>
#include <wx/tglbtn.h>
// end wxGlade

class Sensor;

class SensorComponentEditor: public wxDialog {
public:
    // begin wxGlade: SensorComponentEditor::ids
    // end wxGlade

    SensorComponentEditor(Sensor *sensor, wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: SensorComponentEditor::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: SensorComponentEditor::attributes
    wxStaticBox* sizer_inout_staticbox;
    wxStaticBox* sizer_sensor_staticbox;
    wxStaticBox* sizer_quantize_staticbox;
    wxStaticBox* sizer_clip_staticbox;
    wxStaticBox* sizer_basic_staticbox;
    wxStaticText* label_name;
    wxTextCtrl* text_ctrl_name;
    wxStaticText* label_type;
    wxTextCtrl* text_ctrl_type;
    wxStaticText* label_order;
    wxTextCtrl* text_ctrl_order;
    wxCheckBox* checkbox_clip;
    wxStaticText* label_clip_min;
    wxTextCtrl* text_ctrl_clip_min;
    wxStaticText* label_clip_max;
    wxTextCtrl* text_ctrl_clip_max;
    wxStaticText* label_2;
    wxTextCtrl* text_ctrl_lag;
    wxStaticText* label_3;
    wxRadioBox* radio_box_noise_type;
    wxStaticText* label_4;
    wxTextCtrl* text_ctrl_2;
    wxStaticText* label_5;
    wxTextCtrl* text_ctrl_4_1;
    wxStaticText* label_7;
    wxTextCtrl* text_ctrl_4;
    wxStaticText* label_8;
    wxStaticText* label_9;
    wxTextCtrl* text_ctrl_5;
    wxStaticText* label_12;
    wxTextCtrl* text_ctrl_8;
    wxStaticText* label_13;
    wxSlider* slider_1;
    wxStaticText* label_14;
    wxStaticText* label_15;
    wxTextCtrl* text_ctrl_6;
    wxStaticText* label_16;
    wxTextCtrl* text_ctrl_7;
    wxStaticText* label_1;
    wxToggleButton* button_invert_input;
    wxTextCtrl* text_ctrl_input_prop;
    wxStaticText* label_output_property;
    wxTextCtrl* text_ctrl_output_prop;
    wxPanel* notebook_1_pane_1;
    wxTextCtrl* text_ctrl_1;
    wxNotebook* notebook_1;
    wxButton* button_OK;
    wxButton* button_Cancel;
    wxButton* button_Help;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void OnCheckboxClip(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnCheckBoxNoiseType(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnBitSliderScroll(wxScrollEvent &event); // wxGlade: <event_handler>
    void OnClickInvertInput(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnButtonPressOK(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnButtonPressCancel(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnButtonPressHelp(wxCommandEvent &event); // wxGlade: <event_handler>

    void GetDataIn(Sensor * g);
    void SetDataOut(Sensor * g);
    bool Show(bool);

private:
    wxString name;
    wxString description;
    wxString order;
    bool clipable;
    wxString clip_max;
    wxString clip_min;

}; // wxGlade: end class

#include "sensor.h"

#endif // SENSORCOMPONENTEDITOR_H
