/////////////////////////////////////////////////////////////////////////////
// Name:        When_Diag.h
// Purpose:     Manager of the When
// Author:      Matthew Gong
// Created:     06/23/2005
// Copyright:   (c) Matthew Gong
// Licence:     GPL licence
/////////////////////////////////////////////////////////////////////////////

#if defined(__GNUG__) && !defined(__APPLE__)
// #pragma interface
#endif

// -*- C++ -*- generated by wxGlade 0.4cvs on Thu Jun 23 17:12:14 2005

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/notebook.h>
// end wxGlade


#ifndef WHEN_DIAG_H
#define WHEN_DIAG_H

enum eComparison
{
  FG_LT = 0,
  FG_LE,
  FG_EQ,
  FG_GE,
  FG_GT,
  FG_NE
};

class Parameter : public wxClientData
{
  public :
    Parameter(){}
    ~Parameter(){}
    wxString name;
    eComparison comparison;
    wxString value;
    wxString GetText() const;
    void Load(JSBSim::Element * el);
    void Save(wxTextOutputStream & out, const wxString & prefix);
};

enum eAction
{
  FG_RAMP = 0,
  FG_STEP,
  FG_EXP
};
enum eType
{
  FG_VALUE = 0,
  FG_DELTA
};

class Set : public wxClientData
{
  public :
    Set(){}
    ~Set(){}
    wxString name;
    eType type;
    wxString value;
    eAction action;
    bool persistent;
    wxString tc;
    wxString GetText() const;
    void Load(JSBSim::Element * el);
    void Save(wxTextOutputStream & out, const wxString & prefix);
};

class WhenData : public wxClientData
{
  public:
    WhenData(){}
    ~WhenData(){}
    
    wxString GetText();
    void Load(JSBSim::Element * el);
    void Save(wxTextOutputStream & out, const wxString & prefix);
    
    std::vector<Parameter> parameters;
    std::vector<Set> sets;
};


class WhenDialog: public wxDialog {
public:
    // begin wxGlade: WhenDialog::ids
    enum {
      ID_PARA_LIST = 24672,
      ID_PARA_APPEND,
      ID_PARA_DEL,
      ID_PARA_APPLY,
      ID_PARA_TEXT,
      ID_PARA_NAME,
      ID_PARA_VALUE,
      ID_SET_NAME,
      ID_SET_VALUE,
      ID_SET_LIST,
      ID_SET_APPEND,
      ID_SET_DEL,
      ID_SET_APPLY,
      ID_SET_TEXT,
      ID_SET_TC
    };
    // end wxGlade

    WhenDialog(wxWindow* parent, int id, const wxString& title=_("Conditon/Action Setup"), const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER);

private:
    // begin wxGlade: WhenDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: WhenDialog::attributes
    wxListBox* list_box_para;
    wxButton* button_para_append;
    wxButton* button_para_del;
    wxButton* button_para_apply;
    wxTextCtrl* text_ctrl_para_name;
    wxButton* button_para_name;
    wxComboBox* combo_box_para_comp;
    wxTextCtrl* text_ctrl_para_value;
    wxButton* button_para_value;
    wxPanel* notebook_main_pane_1;
    wxListBox* list_box_set;
    wxButton* button_set_append;
    wxButton* button_set_del;
    wxButton* button_set_apply;
    wxTextCtrl* text_ctrl_set_name;
    wxButton* button_set_name;
    wxStaticText* label_set_eq;
    wxTextCtrl* text_ctrl_set_value;
    wxButton* button_set_value;
    wxStaticText* label_set_type;
    wxComboBox* combo_box_set_type;
    wxStaticText* label_set_action;
    wxComboBox* combo_box_set_action;
    wxStaticText* label_set_tc;
    wxTextCtrl* text_ctrl_set_tc;
    wxButton* button_set_tc;
    wxCheckBox* checkbox_set_persist;
    wxPanel* notebook_main_pane_2;
    wxNotebook* notebook_main;
    wxButton* button_ok;
    wxButton* button_cancel;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void OnSelectPara(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnAppendPara(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnDelPara(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnApplyPara(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnSelectSet(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnAppendSet(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnDelSet(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnApplySet(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnParaName(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnParaValue(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnSetName(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnSetValue(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnSetTC(wxCommandEvent &event); // wxGlade: <event_handler>

protected:
    void update_para();
    void apply_para();
    void update_set();
    void apply_set();
public:
    void Load(WhenData * data=NULL );
    WhenData * Save();
    
}; // wxGlade: end class


#endif // WHEN_DIAG_H
