/////////////////////////////////////////////////////////////////////////////
// Name:        AeroDynamics_Diag.h
// Purpose:     Dialog for AeroDynamics
// Author:      Matthew Gong
// Created:     05/08/2005
// Copyright:   (c) Matthew Gong
// Licence:     GPL licence
/////////////////////////////////////////////////////////////////////////////

#if defined(__GNUG__) && !defined(__APPLE__)
// #pragma interface
#endif

// -*- C++ -*- generated by wxGlade 0.3.5.1 on Sun May  8 19:01:46 2005

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade


#ifndef AERODYNAMICS_DIAG_H
#define AERODYNAMICS_DIAG_H

class TreeItemData_aerodynamics;
class AeroDynamicsDialog: public wxDialog {
public:
    // begin wxGlade: AeroDynamicsDialog::ids
    enum {
      ALPHA_LIMITS = 12500,
      HYSTERESIS_LIMITS
    };
    // end wxGlade

    AeroDynamicsDialog(wxWindow* parent, int id, const wxString& title=_("AeroDynamics Properties"), const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxSize(220, 330), long style=wxDEFAULT_DIALOG_STYLE);
    void Load(const TreeItemData_aerodynamics * data);
    void Save(TreeItemData_aerodynamics * data);

private:
    // begin wxGlade: AeroDynamicsDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: AeroDynamicsDialog::attributes
    wxStaticBox* sizer_2_copy_staticbox;
    wxStaticBox* sizer_2_staticbox;
    wxCheckBox* checkbox_a_enable;
    wxStaticText* label_a_min;
    wxTextCtrl* text_ctrl_a_min;
    wxStaticText* label_a_max;
    wxTextCtrl* text_ctrl_a_max;
    wxCheckBox* checkbox_h_enable;
    wxStaticText* label_h_min;
    wxTextCtrl* text_ctrl_h_min;
    wxStaticText* label_h_max;
    wxTextCtrl* text_ctrl_h_max;
    wxButton* button_ok;
    wxButton* button_cancel;
    // end wxGlade

    wxString alpha_max, alpha_min, hysteresis_max, hysteresis_min;

    void OnEnableA(wxCommandEvent & event);
    void OnEnableH(wxCommandEvent & event);

    DECLARE_EVENT_TABLE() 
};


#endif // AERODYNAMICS_DIAG_H
