/////////////////////////////////////////////////////////////////////////////
// Name:        Engine_Diag.h
// Purpose:     Dialog for General Engine
// Author:      Matthew Gong
// Created:     07/26/2005
// Copyright:   (c) Matthew Gong
// Licence:     GPL licence
/////////////////////////////////////////////////////////////////////////////

#if defined(__GNUG__) && !defined(__APPLE__)
// #pragma interface
#endif

// -*- C++ -*- generated by wxGlade 0.4cvs on Tue Jun 28 16:57:11 2005

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade


#ifndef ENGINE_DIAG_H
#define ENGINE_DIAG_H

#include "FGXMLParse.h"

extern bool newDirect(const wxString & filename);

class EngineDialog: public wxDialog {
public:

    EngineDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

protected :
    JSBSim::FGXMLParse controls_file_parser;
    wxString filename;

public :
    virtual bool Load(const wxString & fn)=0;
    virtual bool Save(const wxString & fn=wxEmptyString)=0;

    wxString GetFilename()const{return filename;}
}; // wxGlade: end class


#endif // ENGINE_DIAG_H
