/////////////////////////////////////////////////////////////////////////////
// Name:        Property_Diag.h
// Purpose:     list of properties
// Author:      Matthew Gong
// Created:     07/05/2005
// Copyright:   (c) Matthew Gong
// Licence:     GPL licence
/////////////////////////////////////////////////////////////////////////////

#if defined(__GNUG__) && !defined(__APPLE__)
// #pragma interface
#endif

// -*- C++ -*- generated by wxGlade 0.4cvs on Tue Jul  5 10:39:29 2005

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/grid.h>
// end wxGlade


#ifndef PROPERTY_DIAG_H
#define PROPERTY_DIAG_H

#include <vector>

struct PropertyItem{
  wxString name;
  wxString desc;
  wxString unit;
  wxString access;
  wxString comment;
};

class PropertyDialog: public wxDialog {
public:
    // begin wxGlade: PropertyDialog::ids
    enum{
      ID_PROPERTY = 21543,
      ID_SHOWALL,
      ID_FILTER
    };
    // end wxGlade

    PropertyDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxSize(830, 620), long style=wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER);

    void Load(const wxArrayString & name, const wxArrayString & desc, const wxArrayString & unit, const wxArrayString & access, const wxArrayString & comment);
    void AddItem(const wxString & name, const wxString & desc = wxEmptyString, const wxString & unit = wxEmptyString, const wxString & access = wxEmptyString, const wxString & comment = wxEmptyString);
    void ClearVar();
    wxString GetResult() const;
    void Update(const wxString & filter = wxEmptyString);
    bool Select(const wxString & name);

private:
    // begin wxGlade: PropertyDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: PropertyDialog::attributes
    wxStaticText* label_sel;
    wxTextCtrl* text_ctrl_sel;
    wxStaticText* label_info;
    wxGrid* grid_prop;
    wxButton* button_filter;
    wxTextCtrl* text_ctrl_filter;
    wxButton* button_showall;
    wxButton* button_ok;
    wxButton* button_cancel;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void OnFilter(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnShowAll(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnOK(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnClickGrid(wxGridEvent &event); // wxGlade: <event_handler>

protected:
    bool pass_filter(const PropertyItem & item, const wxString & filter);
    std::vector<PropertyItem> properties;
    unsigned size;
    
}; // wxGlade: end class


#endif // PROPERTY_DIAG_H
