/////////////////////////////////////////////////////////////////////////////
// Name:        Axis_Diag.h
// Purpose:     Dialog for Axis
// Author:      Matthew Gong
// Created:     05/08/2005
// Copyright:   (c) Matthew Gong
// Licence:     GPL licence
/////////////////////////////////////////////////////////////////////////////

#if defined(__GNUG__) && !defined(__APPLE__)
// #pragma interface
#endif

// -*- C++ -*- generated by wxGlade 0.3.5.1 on Sun May  8 20:23:02 2005

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade


#ifndef AXIS_DIAG_H
#define AXIS_DIAG_H

class TreeItemData_axis;
class AxisDialog: public wxDialog {
public:
    // begin wxGlade: AxisDialog::ids
    // end wxGlade

    AxisDialog(wxWindow* parent, int id, const wxString& title=_("Axis Properties"), const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxSize(200,170), long style=wxDEFAULT_DIALOG_STYLE);
    void Load(const TreeItemData_axis * data);
    void Save(TreeItemData_axis * data);

private:
    // begin wxGlade: AxisDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: AxisDialog::attributes
    wxStaticText* label_name;
    wxComboBox* combo_box_name;
    wxStaticText* label_unit;
    wxComboBox* combo_box_unit;
    wxButton* button_ok;
    wxButton* button_cancel;
    // end wxGlade
};


#endif // AXIS_DIAG_H
